#! usr/bin/env php
<?php

namespace Structural\Composite;

require_once 'vendor/autoload.php';

$root = new Composite('root');

try {
    $root->add(new Composite('root'));
    $root->add(new Leaf('first'));
    $root->add(new Leaf('second'));

    $root->getChild('root')->add(new Leaf('first'));
    $root->getChild('root')->add(new Leaf('second'));
    $root->getChild('root')->add(new Composite('root'));
    $root->getChild('root4');

    print_r($root);
} catch (\Exception $e) {
    echo 'Caught exception: ', $e->getMessage(), "\n";
}
